# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_features'),
        ('features', '0002_features_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='cart',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
    ]