# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bugs',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]